baseURL = "https://flat-earth.netlify.com"
disableLanguages = ["fr"]
disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "meghna-hugo"
title = "Flat Earth"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2022"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.main]]
name = "About"
url = "#about"
weight = 1
[[Languages.en.menu.main]]
name = "Token"
url = "#token"
weight = 2
[[Languages.en.menu.main]]
name = "Proofs"
url = "#portfolio"
weight = 3
[[Languages.en.menu.main]]
name = "Whitepaper"
url = "#whitepaper"
weight = "4"
[[Languages.en.menu.main]]
name = "Contact"
url = "#contact"
weight = "5"
[params]
author = "TJ"
description = "Flat Earth Coin: The Proof is in the Pudding"
google_analytics_id = ""
logo = "images/flatbig-2.png"
post_share = false
social = []
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = false
preloader = "images/flatbig-2.png"
